const CONFIG={launch:"2026-08-19T17:00:00Z",ca:"",pump:""};
const archives=[
["001","DEC 2024","VINTAGE ASH TEA","THEY MADE A PETITION 😭","A Change.org petition called for Ash Trevino to be removed from social media. Claims in the petition remain attributed to its authors.","https://www.change.org/p/ban-ash-trevino-remove-from-social-media"],
["002","ARCHIVE","THE RABBIT HOLE","THE DARK SIDE OF INTERNET MOMS","A background feature collecting earlier Ashley Trevino internet lore and its own source material.","https://thetigernews.org/10944/entertainment/the-dark-side-of-internet-moms-ash-trevinos-story/"],
["003","ARCHIVE","THE FAME FILE","HOW ASHLEY TREVINO GOT FAMOUS","An explainer for newcomers trying to understand how the Ashley Trevino story became a recurring online spectacle.","https://fhsphoenix.org/ashley-trevino-fame/"],
["004","AUG 2026","PROSECUTORS CLAIM","THE 50–75 INMATES HEADLINE","Complex reported prosecutors' allegation that Trevino had been romantically linked to 50–75 inmates. The claim remains explicitly attributed.","https://www.complex.com/pop-culture/a/jaelaniturnerwilliams/ash-trevino-relationships-75-inmates"],
["005","AUG 2026","COURT FILE","THE GUILTY PLEA","A Dallas Morning News report covering Trevino's guilty plea. The linked article may require a subscription.","https://www.dallasnews.com/news/courts/article/north-texas-influencer-ash-trevino-guilty-plea-22385193.php"],
["006","VIDEO","TIMELINE FILE","THE TIKTOK CLIP","A short-form clip preserved as part of the living archive. Context stays linked to the original post.","https://vt.tiktok.com/ZSVjnb32e/"],
["007","PODCAST","LONG-FORM LORE","THE SERIALOUSLY FILE","A podcast transcript containing Ashley Trevino discussion among several internet stories.","https://podscripts.co/podcasts/serialously/230-tiktoks-ashley-trevino-gf-found-decapitated-lively-vs-baldoni-stabbed-over-a-sandwich-new-orleans-attack"]
];
document.getElementById("grid").innerHTML=archives.map(x=>`<article class="card"><div class="thumb">ARCHIVE #${x[0]}</div><div class="meta"><span>${x[2]}</span><span>${x[1]}</span></div><h3>${x[3]}</h3><p>${x[4]}</p><a href="${x[5]}" target="_blank" rel="noopener">VIEW THE RECEIPT →</a></article>`).join("");
function tick(){let d=new Date(CONFIG.launch)-new Date(),el=document.getElementById("clock");if(d<=0){el.textContent="00 : 00 : 00 : 00";if(CONFIG.ca){document.getElementById("ca").textContent=CONFIG.ca;document.getElementById("ca2").textContent=CONFIG.ca}if(CONFIG.pump){let p=document.getElementById("pump");p.href=CONFIG.pump;p.classList.remove("disabled");p.textContent="VIEW ON PUMP.FUN →"}return}let D=Math.floor(d/864e5);d%=864e5;let H=Math.floor(d/36e5);d%=36e5;let M=Math.floor(d/6e4);let S=Math.floor(d%6e4/1e3);el.textContent=[D,H,M,S].map(n=>String(n).padStart(2,"0")).join(" : ")}tick();setInterval(tick,1000);